[IMP] sale_order_weight_cost: add total cost of sale order lines
avanzosc/sale-addons pull request #113
Opened 2020-07-22 11:45 UTC by adrianrevilla009

2020-07-22 12:03 UTC, alfredoavanzosc approved these changes
:+1:

2020-07-22 13:59 UTC, oihane requested changes

2020-07-22 13:59 UTC, oihane commented on sale_order_weight_cost/models/sale_order.py
> +        for sale in self:
No es lo normal, pero por seguridad yo pondria que solo lo ejecute cuando haya `order_line`
```python
for sale in self.filtered("order_line"):
```

2020-07-22 13:59 UTC, oihane commented on sale_order_weight_cost/models/sale_order.py
> +            sale.total_line_cost = sum(sale.order_line.mapped('cost'))
Tienes que poner el `mapped` delante del `order_line` porque en este caso es un `one2many`
```python
sale.total_line_cost = sum(sale.mapped("order_line.cost"))
```

2020-07-22 13:59 UTC, oihane commented on sale_order_weight_cost/views/sale_order_views.xml
> +                position="before">
Puedes ponerlo en una sola línea
```xml
<xpath expr="//field[@name='amount_total']" position="before">
```

y si no me equivoco
```xml
<field name="amount_total" position="after">
```

El xpath se usa cuando el campo está duplicado

2020-07-22 13:59 UTC, oihane commented on sale_order_weight_cost/i18n/es.po
> +msgstr "Coste total de las líneas de pedido de venta"
Llámalo simplemente `Coste total` porque si no te va a fastidiar el tree

2020-07-23 07:09 UTC, adrianrevilla009 commented on sale_order_weight_cost/i18n/es.po
> +msgstr "Coste total de las líneas de pedido de venta"
modificado @oihane

2020-07-23 08:45 UTC, oihane approved these changes

2020-07-23 09:23 UTC, merged