[ADD] sale_student_event: Student and event in sale order line.
avanzosc/sale-addons pull request #147
Opened 2021-04-21 13:26 UTC by Berezi

2021-04-21 13:32 UTC, oihane requested changes

2021-04-21 13:32 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +        comodel_name='res.partner', store=True)
no usar SCHOOL, usar EDUCATION CENTER

2021-04-21 13:37 UTC, Berezi commented on sale_student_event/models/sale_order_line.py
> +        comodel_name='res.partner', store=True)
Realizado lo solicitado. Eskerrik asko.

2021-04-21 13:40 UTC, oihane requested changes
Falta corregir las vistas y las traducciones

2021-04-21 14:00 UTC, Berezi commented on sale_student_event/models/sale_order_line.py
> +        comodel_name='res.partner', store=True)
> Falta corregir las vistas y las traducciones

Realizado lo solicitado

2021-04-21 14:37 UTC, oihane requested changes, later dismissed

2021-04-21 14:37 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +            sale.partner_id = sale.student_id.commercial_partner_id
Esto no tiene sentido, además de que creo que el campo `partner_id` no está en lineas

El **cliente** se establece en cabecera, y los **estudiantes** deberían de estar filtrados por ese **cliente**

cc @anajuaristi

2021-04-21 14:41 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +            sale.partner_id = sale.student_id.commercial_partner_id
Para el dominio, puedes mirar si se puede usar el **order_partner_id**

2021-04-22 07:21 UTC, Berezi commented on sale_student_event/models/sale_order_line.py
> +            sale.partner_id = sale.student_id.commercial_partner_id
Eskerrik asko @oihane , @anajuaristi nos dijo que quitáramos todo.

2021-04-22 07:30 UTC, anajuaristi approved these changes

2021-04-22 07:36 UTC, alfredoavanzosc approved these changes
:+1:

2021-04-22 07:36 UTC, Daniel-CA approved these changes

2021-04-22 08:03 UTC, merged