[IMP] sale_student_event: Is member boolean in event and sale order l…
avanzosc/sale-addons pull request #150
Opened 2021-05-11 12:07 UTC by Berezi

…ine.

2021-05-11 12:08 UTC, Berezi commented
@alfredoavanzosc @oihane @anajuaristi @Daniel-CA review please.

2021-05-11 13:19 UTC, anajuaristi approved these changes

2021-05-11 13:39 UTC, oihane requested changes

2021-05-11 13:39 UTC, oihane commented on sale_student_event/models/sale_order.py
> +    allowed_partners = fields.Many2many(
campo m2m siempre _ids

2021-05-11 13:39 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +    allowed_partners = fields.Many2many(
campo m2m siempre _ids

2021-05-11 13:39 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +    allowed_products = fields.Many2many(
campo m2m siempre _ids

2021-05-11 14:07 UTC, oihane commented on sale_student_event/models/sale_order_line.py
> +    allowed_partners = fields.Many2many(
para el calculo de los estudiantes permitidos, la función sería la siguiente:
```python
    @api.depends("order_id", "order_id.partner_id",
                 "order_id.partner_id.child_id")
    def _compute_allowed_partners(self):
        for sale in self:
            partners = sale.order_id.partner_id | sale.mapped(
                "order_id.partner_id.child_ids")
            sale.allowed_partner_ids = [(6, 0, partners.ids)]
```

de esa manera se hace el calculo en la línea.

2021-05-11 14:07 UTC, oihane commented on sale_student_event/views/sale_order_views.xml
> +             </xpath>
Si se tiene en cuenta que el campo allowed_products (que debe llamarse allowed_product_ids) y ese campo no es calculado ni es visible para rellenarlo, NO SE PUEDEN METER LINEAS.

2021-05-11 14:10 UTC, Berezi commented
@oihane @Daniel-CA @alfredoavanzosc @anajuaristi review please.

2021-05-11 14:43 UTC, oihane requested changes
Los cambios hay que probarlos en local, ya sea entrando al odoo, o ejecutando tests.

Los últimos cambios realizados, no has aplicado el cambio de nombre en la vista

2021-05-12 07:11 UTC, Berezi commented
@anajuaristi @alfredoavanzosc @Daniel-CA @oihane review please

2021-05-12 07:28 UTC, alfredoavanzosc approved these changes
:+1:

2021-05-12 08:22 UTC, oihane requested changes, later dismissed
Sigue estando lo del pedido, esto como está no se puede utilizar

2021-05-12 08:38 UTC, Berezi commented on sale_student_event/views/sale_order_views.xml
> +             </xpath>
en la línea 10, ya esta puesto el campo: <field name="allowed_products_ids" invisible="1"/>
Lo que me estas diciendo en la línea 23, cambia el atributo "domain".

2021-05-12 09:39 UTC, oihane commented on sale_student_event/views/sale_order_views.xml
> +             </xpath>
El campo no es computed, ni related, y está definido como "invisible" por lo que su valor será FALSE, por lo tanto NO SE PUEDE SELECCIONAR NINGUN PRODUCTO.

2021-05-12 13:32 UTC, merged