[FIX] sale_order_line_contract: Put "copy=False" in field "Contract l…
avanzosc/sale-addons pull request #158
Opened 2021-06-16 11:34 UTC by alfredoavanzosc

…ine" of sale order line object.

No copiar el campo "Línea contrato" del objeto "líneas de pedido de venta", cuando se duplica un pedido de venta.

@avanzosc/developers review please.

2021-06-16 12:49 UTC, Daniel-CA approved these changes

2021-06-16 12:50 UTC, mikelarre approved these changes

2021-06-16 14:28 UTC, oihane requested changes, later dismissed
Separando los test no arreglas el bug, si instalas el modulo sale_order_line_contract (sin hacer nada más) crearas contrato para todo lo que vendas a partir de ese momento, y te fallará en todas las ventas. Fíjate en el código donde se le indica de crear las lineas de contrato.

2021-06-16 15:18 UTC, oihane commented
Antes de subirlo, pruebalo en local, el test del modulo `sale_order_line_amount_control` está mal, fijate que le pasa 0,5 y solo salta el error cuando es 1,0

2021-06-16 15:21 UTC, oihane commented
Y también cascarán `sale_required_shipping_address` y `sale_order_from_picking`

2021-06-17 07:48 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +            no_price_unit_control=True).action_confirm()
No puedes hacer esto con todos los módulos que no pasen el test por el otro modulo. Tienes que hacer que aquel modulo no tenga impacto. Puedes seguir el ejemplo que encontrarás en odoomrp-wip
https://github.com/odoomrp/odoomrp-wip/blob/8.0/product_variants_no_automatic_creation/models/product_template.py#L56

2021-06-17 10:52 UTC, merged