[IMP] sale_order_event_attendee: search event order by line ticket
avanzosc/sale-addons pull request #189
Opened 2021-10-28 09:43 UTC by leiremartinezdesantos

2021-10-28 10:16 UTC, alfredoavanzosc approved these changes
:+1:

2021-10-28 15:46 UTC, anajuaristi requested changes

2021-10-28 15:46 UTC, anajuaristi commented on sale_order_event_attendee/models/event.py
> +                    line, order = record.get_event_order(select_ticket)
Hemen
```python
line, order = record.get_event_order(select_ticket)

if not line --> 
    if not order --> 
        order = self.env['sale.order'].sudo().create({'partner_id': self.partner_id.id})
    line = 
        self.env['sale.order.line'].sudo().create(
                            {
                                'product_id': record.event_ticket_id.product_id.id,
                                'event_id': record.event_id.id,
                                'event_ticket_id': record.event_ticket_id.id,
                                'name': record.event_ticket_id.name,
                                'order_id': order.id,
                                'product_uom':
                                    record.event_ticket_id.product_id.uom_id.id})

record.write({'sale_order_line_id': line.id,
              'sale_order_id': order.id})


```
Listo... ez dago  programazio gehiagorik action_confirm bukaera arte

2021-10-28 15:46 UTC, anajuaristi commented on sale_order_event_attendee/models/event.py
>              if select_ticket:
if not order, kendu... zuzenean exekutatu record.get_event_order(select ticket)

2021-11-08 07:36 UTC, Daniel-CA approved these changes

2021-11-10 12:11 UTC, alfredoavanzosc commented
Se cierra este PR, y se crea este nuevo https://github.com/avanzosc/sale-addons/pull/191

2021-11-10 12:11 UTC, closed without merging