[ADD] sale_margin_usability: Mostrar el total coste de las líneas en …
avanzosc/sale-addons pull request #280
Opened 2023-07-20 04:57 UTC by alfredoavanzosc

…los pedidos de venta, y en la vista tree de los pedidos de venta.

2023-07-20 04:58 UTC, alfredoavanzosc commented
CLM7393

2023-07-20 12:30 UTC, oihane submitted a review, later dismissed
* hacer el sumatorio del coste unitario en la vista de las lineas no aporta información real
* sumar el precio de coste unitario de las lineas para mostrar en el pedido no es real

Si debe ser así no puede ser un modulo genérico, ya que solo valdría para casos en los que solo se vende una línea de una unidad.

cc @anajuaristi

2023-07-20 12:39 UTC, anajuaristi commented
Correcto. Faltaría multiplicar el coste unitario por el número de unidades. Y eso iría al total.

2023-07-20 13:55 UTC, oihane requested changes, later dismissed
No se ve el total de coste en el formulario de pedido de venta

2023-07-21 06:38 UTC, anajuaristi approved these changes

2023-07-21 06:38 UTC, merged