[IMP] sale_import_wizard: Poner direcciones despues de crear pedido d…
avanzosc/sale-addons pull request #320
Opened 2023-11-28 14:10 UTC by alfredoavanzosc

…e venta.

2023-11-28 14:11 UTC, alfredoavanzosc commented
CLM8339

2023-11-28 15:44 UTC, oihane requested changes, later dismissed

2023-11-28 15:44 UTC, oihane commented on sale_import_wizard/models/sale_order_import_line.py
> +            values["partner_shipping_id"] = self.sale_delivery_address_id.id
Si añades esto al VALS antes de hacer el create, no deberás hacer un write.

2023-11-29 11:50 UTC, anajuaristi approved these changes

2023-11-29 11:51 UTC, merged