[ADD] sale_order_rental: This module put the start date, end date and…
avanzosc/sale-addons pull request #45
Opened 2019-07-10 10:42 UTC by OihanaLarranaga

@oihane

2019-07-10 10:44 UTC, oihane commented on sale_order_rental/README.rst
> +<https://github.com/avanzosc/odoo-addons/issues>`_. In case of trouble, please
Al loro, que lo has subido a sale-addons

2019-07-10 12:06 UTC, alfredoavanzosc commented
@api.model
    def _calc_line_quantity(self, line):
        qty = super(SaleOrderLine, self)._calc_line_quantity(line)
        if line.performance and line.apply_performance:
            qty = qty * line.performance
        return qty

2019-07-10 12:18 UTC, oihane commented
La función que menciona @alfredoavanzosc no te sirve en v12, no existe.

2019-07-10 12:21 UTC, oihane commented on sale_order_rental/models/sale_order.py
> +    def _compute_amount(self):
La función debe ser como sigue:
```python
    @api.depends('product_uom_qty', 'discount', 'price_unit', 'tax_id',
                 'rental_days')
    def _compute_amount(self):
        for line in self:
            if line.rental_days:
                price = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
                taxes = line.tax_id.compute_all(
                    price, line.order_id.currency_id,
                    line.product_uom_qty * line.rental_days,
                    product=line.product_id,
                    partner=line.order_id.partner_shipping_id)
                line.update({
                    'price_tax': sum(
                        t.get('amount', 0.0) for t in taxes.get('taxes', [])),
                    'price_total': taxes['total_included'],
                    'price_subtotal': taxes['total_excluded'],
                })
            else:
                super(SaleOrderLine, self)._compute_amount()
```

2019-07-10 12:28 UTC, oihane commented on sale_order_rental/models/sale_order.py
> +    def _compute_amount(self):
Acabo de editarlo, tenia un fallo, ups

2019-07-11 15:51 UTC, oihane requested changes
Revisa el PR porque has subido el modulo contra la raiz eliminando TODO lo que hay aparte

2019-07-24 10:22 UTC, OihanaLarranaga commented
@avanzosc/developers review please

2019-07-24 10:46 UTC, oihane commented
Has subido cambios que no corresponden al modulo que se quiere añadir.

2019-07-24 10:56 UTC, oihane requested changes

2019-07-24 10:56 UTC, oihane commented on sale_order_rental/models/account_invoice.py
> +    sale_order_line_id = fields.Many2one(
Basate en campo que ya existe para obtener la fecha, no es necesario poner de nuevo este campo.

2019-07-24 10:56 UTC, oihane commented on sale_order_rental/models/account_invoice.py
> +        string='', related='sale_order_id.expected_delivery_date')
No dejes el string vacio, si eso no lo pongas.

2019-07-24 10:56 UTC, oihane commented on sale_order_rental/models/account_invoice.py
> +    rental_days = fields.Integer(
Mismo caso que con expected_delivery_date

2019-07-24 10:56 UTC, oihane commented on sale_order_rental/models/sale_order.py
> +        res = super(SaleOrder, self).action_confirm()
No estas teniendo en cuenta que no todos los pedidos tienen porque se de alquiler, por lo que si el campo está vacio nunca podrás validar dicho pedido, dado que el picking generado no tendrá ese dato informado, y por lo tanto cascará al intentar añadir la fecha, además solo deberia de generarse la devolución del alquilado.

2019-07-30 06:59 UTC, closed without merging