[ADD] sale_order_rental: This module put the start date, end date and…
avanzosc/sale-addons pull request #50
Opened 2019-07-30 07:07 UTC by OihanaLarranaga

2019-07-30 07:58 UTC, OihanaLarranaga commented
@oihane no entiendo los errores que me da travis

2019-08-08 09:56 UTC, OihanaLarranaga commented
@avanzosc/developers  review please

2019-08-08 13:46 UTC, oihane requested changes

2019-08-08 13:46 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +        invoice_line._compute_expected_delivery_date()
No debes "ejecutar" el compute si no leer el campo y validar que el valor es correcto, de esa manera ejecutará el metodo, lo mismo con el resto de líneas.

2019-08-08 13:46 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
SI ejecutas un onchange tendrás que validar que lo que hace es correcto, no simplemente ejecutarlo, lo mismo con la siguiente línea.

2019-08-08 13:46 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +            {'task_id': [(6, 0, self.tax.ids)]})
¿¿Porque pones 'task_id'?? eso son tareas y estas añadiendo impuestos.

2019-09-05 13:43 UTC, OihanaLarranaga commented
Realizadas las mejoras solicitadas por @oihane

2019-09-06 06:20 UTC, OihanaLarranaga commented on sale_order_rental/tests/test_sale_order_rental.py
> +        invoice_line._compute_expected_delivery_date()
Tema realizado @oihane , eskerrik asko.

2019-09-06 06:20 UTC, OihanaLarranaga commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
Tema realizado @oihane , necesito que me desbloquees el PR. Eskerrik asko.

2019-09-06 06:20 UTC, OihanaLarranaga commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
Tema realizado @oihane , necesito que me desbloquees el PR. Eskerrik asko.

2019-09-06 06:21 UTC, alfredoavanzosc approved these changes
:+1:

2019-09-09 09:47 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
si lo que haces es eliminar los campos en el pedido, y eso tiene que hacer que los campos en las líneas sean vacíos no es lo que estas validando. No es correcto

2019-09-12 09:40 UTC, OihanaLarranaga commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
Realizados los cambios solicitados por @oihane

2019-09-12 12:57 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
pero cambia el campo en la línea de pedido, no estas comprobando las lineas de pedido, si no las facturas.

2019-09-12 12:58 UTC, oihane commented on sale_order_rental/tests/test_sale_order_rental.py
> +        for invoice_line in self.sale_order.invoice_ids:
si buscas facturas (invoice) no pongas `invoice_line` lleva a error

2019-09-13 09:26 UTC, OihanaLarranaga commented on sale_order_rental/tests/test_sale_order_rental.py
> +        self.sale_order.onchange_expected_end_date()
Realizados los cambios solicitados por @oihane

2019-11-20 15:34 UTC, oihane approved these changes

2019-11-20 15:34 UTC, merged